name: Release

on:
  push:
    branches: [main, master]  # Runs on pushes to these branches
#    tags:
#      - 'v*.*.*'  # Runs on version tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Install system dependencies for R packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      # Step 3: Set up R
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      # Step 4: Create GitHub Release (only on tag pushes)
      - name: Create GitHub Release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automatic release for version ${{ github.ref }}.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub token
