name: R-CMD-check and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Run on version tags

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Set up R
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install pak and devtools using pak::pak
      - name: Install dependencies with pak
        run: |
          Rscript -e 'install.packages("pak")'
          Rscript -e 'pak::pak("devtools")'

      # Step 4: Run R CMD check
      - name: Run R CMD check
        run: R CMD check .

      # Step 5: Create a GitHub release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}  # Use the tag that triggered the workflow
          release_name: Release ${{ github.ref }}
          body: |
            Automatic release for version ${{ github.ref }}.
          draft: false
          prerelease: false
